[build]
  base = "."                 # The base is current folder (TenziesReact)
  publish = "dist"           # This is where the built files are located
  command = "npm run build"  # Your build command for React


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200